spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: resource-processor

  cloud:
    config:
      enabled: false

server:
  port: 8008

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka