spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

  application:
    name: resource-processor

  cloud:
    config:
      enabled: false

server:
  port: 8008

eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}